### ISSUE TITLE
'twistd klein' plugin

### ISSUE THREAD

**Issue by glyph** [MostAwesomeDude/klein#7]
I want to take the example at the top of the readme, clip off the 'run' function at the bottom, then do

    twistd klein myklein.py --port tcp:8080

so as to get all the usual goodness of listening on an endpoint.

Although what I *really* want is the ability to do

    twistd klein --personal

just like I can do

    twistd web --personal ...

So I can run awesome klein apps on twistedmatrix.com.

**Comment by MostAwesomeDude** [comment]
Moved to twisted/klein.
