### ISSUE TITLE
request.url_for not working

### ISSUE THREAD

**Issue by rboulton** [MostAwesomeDude/klein#8]
Reading the code history, it looks like reverse routing is meant to be, or has been, available via request.url_for().  This is defined on KleinRequest, but KleinRequest doesn't seem to be available from request handlers.

If this is somehow already possible, adding an example to the documentation would be great.

**Comment by MostAwesomeDude** [comment]
Hi!

I apologize for not responding in a timely manner.

According to https://github.com/twisted/klein/blob/master/NEWS.rst#021---2013-07-23 you should be able to do this now with ``IKleinRequest(request).url_for``. I haven't personally tried this, though.

If you need to file further issues, please do so on twisted/klein.

Sorry again, and thank you for flying Twisted!
